language: node_js
node_js:
  - "8.15.0"
services:
 - postgresql
before_script:
 - psql -c "create user hadad with PASSWORD 'dusmel';" -U postgres
 - psql -c 'create database politico;' -U postgres
script:
  - npx eslint server
  - npm test
after_success: npm run coverage
